export const vinylTestData = {
  1: {
    title: 'Abbey Road',
    author: 'The Beatles',
    description: 'Iconic final studio album by the Beatles, released in 1969.',
    price: 25.99,
    quantity: 9,
  },
  2: {
    title: 'Thriller',
    author: 'Michael Jackson',
    description: 'Best-selling album of all time, released in 1982.',
    price: 20.49,
    quantity: 7,
  },
  3: {
    title: 'The Dark Side of the Moon',
    author: 'Pink Floyd',
    description: 'Classic rock masterpiece, released in 1973.',
    price: 30.99,
    quantity: 5,
  },
  4: {
    title: 'Rumours',
    author: 'Fleetwood Mac',
    description:
      'Highly acclaimed album known for its emotional lyrics, released in 1977.',
    price: 28.99,
    quantity: 11,
  },
  5: {
    title: 'Led Zeppelin IV',
    author: 'Led Zeppelin',
    description:
      'Fourth studio album by Led Zeppelin, featuring Stairway to Heaven, released in 1971.',
    price: 22.99,
    quantity: 8,
  },
  6: {
    title: 'Back in Black',
    author: 'AC/DC',
    description:
      'One of the best-selling albums in history, released in 1980 after the death of Bon Scott.',
    price: 27.99,
    quantity: 6,
  },
  7: {
    title: 'Hotel California',
    author: 'Eagles',
    description:
      'Iconic rock album with the hit title track, released in 1976.',
    price: 24.99,
    quantity: 10,
  },
  8: {
    title: 'Purple Rain',
    author: 'Prince',
    description: 'Soundtrack album to the film Purple Rain, released in 1984.',
    price: 26.49,
    quantity: 4,
  },
  9: {
    title: 'Nevermind',
    author: 'Nirvana',
    description: 'Breakthrough album of the grunge movement, released in 1991.',
    price: 23.99,
    quantity: 13,
  },
  10: {
    title: 'The Wall',
    author: 'Pink Floyd',
    description: 'Rock opera double album by Pink Floyd, released in 1979.',
    price: 31.99,
    quantity: 3,
  },
  11: {
    title: 'Born to Run',
    author: 'Bruce Springsteen',
    description: 'Third studio album by Bruce Springsteen, released in 1975.',
    price: 21.99,
    quantity: 12,
  },
  12: {
    title: 'The Queen Is Dead',
    author: 'The Smiths',
    description: 'Critically acclaimed album by The Smiths, released in 1986.',
    price: 29.99,
    quantity: 8,
  },
  13: {
    title: 'Pet Sounds',
    author: 'The Beach Boys',
    description: 'Influential album in the history of music, released in 1966.',
    price: 32.99,
    quantity: 7,
  },
  14: {
    title: 'Born in the U.S.A.',
    author: 'Bruce Springsteen',
    description: 'Seventh studio album by Bruce Springsteen, released in 1984.',
    price: 25.49,
    quantity: 9,
  },
  15: {
    title: "Sgt. Pepper's Lonely Hearts Club Band",
    author: 'The Beatles',
    description: 'Groundbreaking album by The Beatles, released in 1967.',
    price: 33.49,
    quantity: 5,
  },
  16: {
    title: 'Exile on Main St.',
    author: 'The Rolling Stones',
    description: 'Double album by The Rolling Stones, released in 1972.',
    price: 26.99,
    quantity: 8,
  },
  17: {
    title: 'London Calling',
    author: 'The Clash',
    description: 'Critically acclaimed album by The Clash, released in 1979.',
    price: 28.49,
    quantity: 6,
  },
  18: {
    title: 'A Night at the Opera',
    author: 'Queen',
    description:
      'Fourth studio album by Queen, featuring Bohemian Rhapsody, released in 1975.',
    price: 29.99,
    quantity: 10,
  },
  19: {
    title: "What's Going On",
    author: 'Marvin Gaye',
    description: 'Concept album addressing social issues, released in 1971.',
    price: 24.99,
    quantity: 7,
  },
  20: {
    title: 'Bridge Over Troubled Water',
    author: 'Simon & Garfunkel',
    description:
      'Fifth and final studio album by Simon & Garfunkel, released in 1970.',
    price: 27.99,
    quantity: 11,
  },
  21: {
    title: 'The Joshua Tree',
    author: 'U2',
    description: 'Fifth studio album by U2, released in 1987.',
    price: 22.99,
    quantity: 5,
  },
  22: {
    title: 'Graceland',
    author: 'Paul Simon',
    description: 'Seventh solo studio album by Paul Simon, released in 1986.',
    price: 28.99,
    quantity: 9,
  },
  23: {
    title: 'Songs in the Key of Life',
    author: 'Stevie Wonder',
    description: 'Eighteenth studio album by Stevie Wonder, released in 1976.',
    price: 30.49,
    quantity: 8,
  },
  24: {
    title: 'Goodbye Yellow Brick Road',
    author: 'Elton John',
    description: 'Seventh studio album by Elton John, released in 1973.',
    price: 26.99,
    quantity: 10,
  },
  25: {
    title: 'Blood on the Tracks',
    author: 'Bob Dylan',
    description: 'Fifteenth studio album by Bob Dylan, released in 1975.',
    price: 25.99,
    quantity: 6,
  },
  26: {
    title: 'A Kind of Magic',
    author: 'Queen',
    description: 'Soundtrack album to the film Highlander, released in 1986.',
    price: 24.49,
    quantity: 7,
  },
  27: {
    title: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars',
    author: 'David Bowie',
    description: 'Concept album by David Bowie, released in 1972.',
    price: 29.99,
    quantity: 4,
  },
  28: {
    title: 'Off the Wall',
    author: 'Michael Jackson',
    description: 'Fifth studio album by Michael Jackson, released in 1979.',
    price: 23.99,
    quantity: 9,
  },
  29: {
    title: 'Court and Spark',
    author: 'Joni Mitchell',
    description: 'Sixth studio album by Joni Mitchell, released in 1974.',
    price: 27.49,
    quantity: 6,
  },
  30: {
    title: 'Hunky Dory',
    author: 'David Bowie',
    description: 'Fourth studio album by David Bowie, released in 1971.',
    price: 26.99,
    quantity: 8,
  },
  31: {
    title: 'The Doors',
    author: 'The Doors',
    description: 'Debut album by The Doors, released in 1967.',
    price: 24.49,
    quantity: 5,
  },
  32: {
    title: 'Moondance',
    author: 'Van Morrison',
    description: 'Third studio album by Van Morrison, released in 1970.',
    price: 28.99,
    quantity: 7,
  },
  33: {
    title: 'Electric Ladyland',
    author: 'Jimi Hendrix',
    description:
      'Third and final studio album by the Jimi Hendrix Experience, released in 1968.',
    price: 31.49,
    quantity: 9,
  },
  34: {
    title: 'Layla and Other Assorted Love Songs',
    author: 'Derek and the Dominos',
    description:
      'Only studio album by Derek and the Dominos, released in 1970.',
    price: 30.99,
    quantity: 8,
  },
  35: {
    title: 'Are You Experienced',
    author: 'Jimi Hendrix',
    description:
      'Debut studio album by the Jimi Hendrix Experience, released in 1967.',
    price: 32.49,
    quantity: 6,
  },
  36: {
    title: 'Blue',
    author: 'Joni Mitchell',
    description: 'Fourth studio album by Joni Mitchell, released in 1971.',
    price: 29.49,
    quantity: 7,
  },
  37: {
    title: 'A Night at the Opera',
    author: 'Queen',
    description: 'Fourth studio album by Queen, released in 1975.',
    price: 33.99,
    quantity: 5,
  },
  38: {
    title: 'Kind of Blue',
    author: 'Miles Davis',
    description: 'Landmark jazz album by Miles Davis, released in 1959.',
    price: 35.49,
    quantity: 10,
  },
  39: {
    title: 'Court and Spark',
    author: 'Joni Mitchell',
    description: 'Sixth studio album by Joni Mitchell, released in 1974.',
    price: 28.99,
    quantity: 8,
  },
  40: {
    title: 'A Night at the Opera',
    author: 'Queen',
    description: 'Fourth studio album by Queen, released in 1975.',
    price: 33.99,
    quantity: 6,
  },
  41: {
    title: 'Kind of Blue',
    author: 'Miles Davis',
    description: 'Landmark jazz album by Miles Davis, released in 1959.',
    price: 35.49,
    quantity: 9,
  },
  42: {
    title: 'Bridge Over Troubled Water',
    author: 'Simon & Garfunkel',
    description:
      'Fifth and final studio album by Simon & Garfunkel, released in 1970.',
    price: 27.99,
    quantity: 7,
  },
  43: {
    title: 'The Joshua Tree',
    author: 'U2',
    description: 'Fifth studio album by U2, released in 1987.',
    price: 22.99,
    quantity: 11,
  },
  44: {
    title: 'Graceland',
    author: 'Paul Simon',
    description: 'Seventh solo studio album by Paul Simon, released in 1986.',
    price: 28.99,
    quantity: 8,
  },
  45: {
    title: 'Songs in the Key of Life',
    author: 'Stevie Wonder',
    description: 'Eighteenth studio album by Stevie Wonder, released in 1976.',
    price: 30.49,
    quantity: 6,
  },
  46: {
    title: 'Goodbye Yellow Brick Road',
    author: 'Elton John',
    description: 'Seventh studio album by Elton John, released in 1973.',
    price: 26.99,
    quantity: 9,
  },
  47: {
    title: 'Blood on the Tracks',
    author: 'Bob Dylan',
    description: 'Fifteenth studio album by Bob Dylan, released in 1975.',
    price: 25.99,
    quantity: 7,
  },
  48: {
    title: 'A Kind of Magic',
    author: 'Queen',
    description: 'Soundtrack album to the film Highlander, released in 1986.',
    price: 24.49,
    quantity: 8,
  },
  49: {
    title: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars',
    author: 'David Bowie',
    description: 'Concept album by David Bowie, released in 1972.',
    price: 29.99,
    quantity: 5,
  },
  50: {
    title: 'Off the Wall',
    author: 'Michael Jackson',
    description: 'Fifth studio album by Michael Jackson, released in 1979.',
    price: 23.99,
    quantity: 10,
  },
};
